from datetime import datetime, timezone
from typing import Dict, Any

def generate_credit_report(profile: Dict[str, Any], analysis: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generates structured credit assessment memorandum for CreditReportTab.
    """
    now = datetime.now(timezone.utc)
    report_id = f"CB-REP-{int(now.timestamp())}"
    generated_date = now.strftime("%B %d, %Y")

    scoring = analysis.get("scoring", {})
    financials = analysis.get("financials", {})
    trust = analysis.get("trust", {})
    score = scoring.get("score", 75)
    name = profile.get("name", "MSME Enterprise")
    months = financials.get("totalMonths", 8)
    duplicates = trust.get("duplicateCount", 0)

    if score >= 80:
        notes = (
            f"Applicant ({name}) demonstrates strong financial momentum and robust positive cash-flow buffers "
            f"across the {months}-month observation timeline. Data trust checks verified cleanly with {duplicates} duplicate entries. "
            f"Suitable for expedited human review for growth-tier working capital facilities."
        )
    elif score >= 65:
        notes = (
            f"Applicant ({name}) exhibits steady operational velocity with disciplined cash flow buffers "
            f"over the {months}-month observation timeline. Data trust checks indicate reliable ledger hygiene with {duplicates} duplicates. "
            f"Recommended for human credit committee review under standard working capital guidelines."
        )
    else:
        risk_title = scoring.get("riskWarnings", [{}])[0].get("title", "recent operational variance") if scoring.get("riskWarnings") else "recent operational variance"
        notes = (
            f"Applicant ({name}) presents elevated risk indicators including revenue volatility or cash-flow compression "
            f"({scoring.get('riskCategory', 'Elevated Risk')}). Underwriter clarification recommended regarding "
            f"{risk_title.lower()} prior to credit facility sanction."
        )

    return {
        "reportId": report_id,
        "generatedDate": generated_date,
        "profile": profile,
        "analysis": analysis,
        "underwriterNotes": notes,
        "summary": analysis.get("summary", {}),
        "scoring": scoring,
        "financials": financials,
        "behaviour": analysis.get("behaviour", {}),
        "trust": trust,
        "story": analysis.get("story", {}),
        "crossSignal": analysis.get("crossSignal", {}),
        "disclaimer": "This document is generated by the CreditBridge Explainable Financial Intelligence Engine for prototype decision-support evaluation. It is not an official CIBIL credit score or bank sanction letter."
    }

